name: node CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
env:
  PATH_FOLDER: /root/ai-vision
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/ai-vision
          git pull origin master
          cd /root/ai-vision/controller-microservice
          npm i
          npm run build
          pm2 delete controller3 -s  || :
          pm2 start /root/ai-vision/controller-microservice/dist/main.js --name controller3

          cd /root/ai-vision/database-microservice
          npm i
          npm run build
          pm2 delete database3 -s  || :
          pm2 start /root/ai-vision/database-microservice/dist/main.js --name database3

          cd /root/ai-vision/mailer-microservice
          npm i
          npm run build
          pm2 delete mailer3 -s  || :
          pm2 start /root/ai-vision/mailer-microservice/dist/main.js --name mailer3